/* php_quicpro_arginfo.h */
/* autogenerated via stub generator from stubs.php */

ZEND_BEGIN_ARG_INFO_EX(arginfo_quicpro_connect, 0, 0, 2)
    ZEND_ARG_TYPE_INFO(0, host, IS_STRING, 0)
    ZEND_ARG_TYPE_INFO(0, port, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_quicpro_close, 0, 0, 1)
    ZEND_ARG_INFO(0, session)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_quicpro_send_request, 0, 0, 2)
    ZEND_ARG_INFO(0, session)
    ZEND_ARG_TYPE_INFO(0, path, IS_STRING, 0)
    ZEND_ARG_TYPE_INFO(0, headers, IS_ARRAY, 1)
    ZEND_ARG_TYPE_INFO(0, body, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_quicpro_receive_response, 0, 0, 2)
    ZEND_ARG_INFO(0, session)
    ZEND_ARG_TYPE_INFO(0, stream_id, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_quicpro_poll, 0, 0, 2)
    ZEND_ARG_INFO(0, session)
    ZEND_ARG_TYPE_INFO(0, timeout_ms, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_quicpro_cancel_stream, 0, 0, 2)
    ZEND_ARG_INFO(0, session)
    ZEND_ARG_TYPE_INFO(0, stream_id, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_quicpro_export_session_ticket, 0, 0, 1)
    ZEND_ARG_INFO(0, session)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_quicpro_import_session_ticket, 0, 0, 2)
    ZEND_ARG_INFO(0, session)
    ZEND_ARG_TYPE_INFO(0, ticket, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_quicpro_set_ca_file, 0, 0, 1)
    ZEND_ARG_TYPE_INFO(0, ca_file, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_quicpro_set_client_cert, 0, 0, 2)
    ZEND_ARG_TYPE_INFO(0, cert_pem, IS_STRING, 0)
    ZEND_ARG_TYPE_INFO(0, key_pem, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_quicpro_get_last_error, 0, 0, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_quicpro_get_stats, 0, 0, 1)
    ZEND_ARG_INFO(0, session)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_quicpro_version, 0, 0, 0)
ZEND_END_ARG_INFO()
