networks:
  fullstack:
    driver: bridge
    ipam:
      config:
        - subnet: 10.30.11.0/24

services:
  ###############################################################################
  #  Reverse-Proxy & Dashboard
  ###############################################################################
  traefik:
    image: traefik:v3.4.0
    container_name: traefik
    hostname: traefik
    init: true
    profiles: ["infra"]
    networks:
      fullstack:
        ipv4_address: 10.30.11.100
    ports:
      - "80:80"              # HTTP  → redirects to HTTPS
      - "443:443"            # HTTPS / HTTP-3  (UDP+TCP)
      - "8080:8080"          # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infra/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./infra/traefik/configuration:/etc/traefik/configuration:ro
      - ./var/traefik/certificates/local-cert.pem:/etc/traefik/certs/local-cert.crt:ro
      - ./var/traefik/certificates/local-key.pem:/etc/traefik/certs/local-key.key:ro
      - ~/.local/share/mkcert/rootCA.pem:/etc/ssl/certs/ca-certificates.crt:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`traefik.local`)"
      traefik.http.routers.traefik.entrypoints: "websecure"
      traefik.http.routers.traefik.tls: "true"
      traefik.http.services.traefik.loadbalancer.server.port: "8080"

  ###############################################################################
  #  QUIC demo server (PHP 8.4 + PECL quicpro_async)
  ###############################################################################
  quic-demo:
    image: quicpro_async.dev/quic-demo:latest
    container_name: quic-demo
    profiles: ["test"]
    networks:
      fullstack:
        ipv4_address: 10.30.11.10
    volumes:
      - ./tests:/workspace/tests:rw
      - ./infra/scripts:/workspace/infra/scripts:rw
      - ./extension:/workspace/extension:rw
      - ./quiche:/workspace/quiche:rw
      - ./benchmarks:/workspace/benchmarks:rw
      - ./var/traefik/certificates:/workspace/var/traefik/certificates:rw
      - ./Makefile:/workspace/Makefile:ro
      - ./infra/demo-server/composer.lock:/workspace/composer.lock:ro
      - ./infra/demo-server/composer.json:/workspace/composer.json:ro
      - ./libcurl:/workspace/libcurl:rw
    environment:
      QUIC_DEMO_HOST: "0.0.0.0"
      QUIC_DEMO_PORT: "4433"
      QUIC_RETRY_PORT: "4434"
    expose:
      - "4433/udp"
      - "4434/udp"
    healthcheck:
      test: ["CMD-SHELL", "nc -z -u 127.0.0.1 4433"]
      interval: 3s
      retries: 10
    labels:
      traefik.enable: "true"
      traefik.http.routers.demo.rule: "Host(`demo.dev`)"
      traefik.http.routers.demo.entrypoints: "websecure"
      traefik.http.routers.demo.tls: "true"
      traefik.http.services.demo.loadbalancer.server.port: "4433"

  ###############################################################################
  #  PHPUnit runners (PHP 8.1 – 8.4) – each exposes its own QUIC endpoint
  ###############################################################################
  php81:
    image: quicpro_async.dev/php81:latest
    container_name: php81-test
    profiles: ["test"]
    networks:
      fullstack:
        ipv4_address: 10.30.11.81
    volumes:
      - ./tests:/workspace/tests:rw
      - ./infra/scripts:/workspace/infra/scripts:rw
      - ./extension:/workspace/extension:rw
      - ./quiche:/workspace/quiche:rw
      - ./benchmarks:/workspace/benchmarks:rw
      - ./var/traefik/certificates:/workspace/var/traefik/certificates:rw
      - ./Makefile:/workspace/Makefile:ro
      - ./infra/php81/composer.lock:/workspace/composer.lock:ro
      - ./infra/php81/composer.json:/workspace/composer.json:ro
      - ./libcurl:/workspace/libcurl:rw
    environment:
      QUIC_DEMO_HOST: "quic-demo"
      QUIC_DEMO_PORT: "4433"
      QUIC_RETRY_PORT: "4434"
    labels:
      traefik.enable: "true"
      traefik.http.routers.api81.rule: "Host(`api.php81.dev`)"
      traefik.http.routers.api81.entrypoints: "websecure"
      traefik.http.routers.api81.tls: "true"
      traefik.http.services.api81.loadbalancer.server.port: "4433"

  php82:
    image: quicpro_async.dev/php82:latest
    container_name: php82-test
    profiles: ["test"]
    networks:
      fullstack:
        ipv4_address: 10.30.11.82
    volumes:
      - ./tests:/workspace/tests:rw
      - ./infra/scripts:/workspace/infra/scripts:rw
      - ./extension:/workspace/extension:rw
      - ./quiche:/workspace/quiche:rw
      - ./benchmarks:/workspace/benchmarks:rw
      - ./var/traefik/certificates:/workspace/var/traefik/certificates:rw
      - ./Makefile:/workspace/Makefile:ro
      - ./infra/php82/composer.lock:/workspace/composer.lock:ro
      - ./infra/php82/composer.json:/workspace/composer.json:ro
      - ./libcurl:/workspace/libcurl:rw
    environment:
      QUIC_DEMO_HOST: "quic-demo"
      QUIC_DEMO_PORT: "4433"
      QUIC_RETRY_PORT: "4434"
    labels:
      traefik.enable: "true"
      traefik.http.routers.api82.rule: "Host(`api.php82.dev`)"
      traefik.http.routers.api82.entrypoints: "websecure"
      traefik.http.routers.api82.tls: "true"
      traefik.http.services.api82.loadbalancer.server.port: "4433"

  php83:
    image: quicpro_async.dev/php83:latest
    container_name: php83-test
    profiles: ["test"]
    networks:
      fullstack:
        ipv4_address: 10.30.11.83
    volumes:
      - ./tests:/workspace/tests:rw
      - ./infra/scripts:/workspace/infra/scripts:rw
      - ./extension:/workspace/extension:rw
      - ./quiche:/workspace/quiche:rw
      - ./benchmarks:/workspace/benchmarks:rw
      - ./var/traefik/certificates:/workspace/var/traefik/certificates:rw
      - ./Makefile:/workspace/Makefile:ro
      - ./infra/php83/composer.lock:/workspace/composer.lock:ro
      - ./infra/php83/composer.json:/workspace/composer.json:ro
      - ./libcurl:/workspace/libcurl:rw
    environment:
      QUIC_DEMO_HOST: "quic-demo"
      QUIC_DEMO_PORT: "4433"
      QUIC_RETRY_PORT: "4434"
    labels:
      traefik.enable: "true"
      traefik.http.routers.api83.rule: "Host(`api.php83.dev`)"
      traefik.http.routers.api83.entrypoints: "websecure"
      traefik.http.routers.api83.tls: "true"
      traefik.http.services.api83.loadbalancer.server.port: "4433"

  php84:
    image: quicpro_async.dev/php84:latest
    container_name: php84-test
    profiles: ["test"]
    networks:
      fullstack:
        ipv4_address: 10.30.11.84
    volumes:
      - ./tests:/workspace/tests:rw
      - ./infra/scripts:/workspace/infra/scripts:rw
      - ./extension:/workspace/extension:rw
      - ./quiche:/workspace/quiche:rw
      - ./benchmarks:/workspace/benchmarks:rw
      - ./var/traefik/certificates:/workspace/var/traefik/certificates:rw
      - ./Makefile:/workspace/Makefile:ro
      - ./infra/php84/composer.lock:/workspace/composer.lock:ro
      - ./infra/php84/composer.json:/workspace/composer.json:ro
      - ./libcurl:/workspace/libcurl:rw
    environment:
      QUIC_DEMO_HOST: "quic-demo"
      QUIC_DEMO_PORT: "4433"
      QUIC_RETRY_PORT: "4434"
    labels:
      traefik.enable: "true"
      traefik.http.routers.api84.rule: "Host(`api.php84.dev`)"
      traefik.http.routers.api84.entrypoints: "websecure"
      traefik.http.routers.api84.tls: "true"
      traefik.http.services.api84.loadbalancer.server.port: "4433"

#  ###############################################################################
#  #  QUIC capture (optional)
#  ###############################################################################
#  tshark:
#    image: quicpro_async.dev/tshark:latest
#    container_name: tshark-capture
#    profiles: ["capture"]
#    networks:
#      fullstack:
#        ipv4_address: 10.30.11.50
#    volumes:
#      - ./captures:/captures
#    command: ["-i", "any", "-w", "/captures/capture.pcapng"]
#
#  ###############################################################################
#  #  Front-end (Hot-reload via Vite)
#  ###############################################################################
#  vue_frontend:
#    image: registry.kreuzung1.de/intelligent-intern/vue-app:latest
#    container_name: vue_frontend
#    profiles: ["frontend"]
#    networks:
#      fullstack:
#        ipv4_address: 10.30.11.120
#    ports:
#      - "8082:5173"
#    volumes:
#      - ./app/typescript/vue/frontend:/app:rw
#    command: ["sh", "-c", "npm install && npm run dev -- --host"]
#    labels:
#      traefik.enable: "true"
#      traefik.http.routers.frontend.rule: "Host(`frontend.dev`)"
#      traefik.http.routers.frontend.entrypoints: "websecure"
#      traefik.http.routers.frontend.tls: "true"
#      traefik.http.services.frontend.loadbalancer.server.port: "5173"