api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls: {}
    http3: {}

tls:
  options:
    default:
      minVersion: VersionTLS13

  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/local-cert.crt
        keyFile: /etc/traefik/certs/local-key.key

  certificates:
    - certFile: /etc/traefik/certs/local-cert.crt
      keyFile: /etc/traefik/certs/local-key.key
      stores:
        - default

providers:
  docker:
    watch: true
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: /etc/traefik/configuration
    watch: true