name: quicpro_async CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-php-81:
    name: Build and Test PHP 8.1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies PHP 8.1
        run: |
          sudo apt-get update -yq
          sudo apt-get install -yq git build-essential autoconf pkg-config re2c bison libssl-dev zlib1g-dev ccache rustc cargo php8.1 php8.1-dev php8.1-xml

      - name: Setup ccache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Cargo vendor
        run: |
          cargo vendor > .cargo/config

      - name: Build & test extension PHP 8.1
        run: |
          phpize
          ./configure --enable-quicpro-sched
          make -j$(nproc)
          make TESTS="-j$(nproc) --show-diff"

  build-php-82:
    name: Build and Test PHP 8.2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies PHP 8.2
        run: |
          sudo apt-get update -yq
          sudo apt-get install -yq git build-essential autoconf pkg-config re2c bison libssl-dev zlib1g-dev ccache rustc cargo php8.2 php8.2-dev php8.2-xml

      - name: Setup ccache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Cargo vendor
        run: |
          cargo vendor > .cargo/config

      - name: Build & test extension PHP 8.2
        run: |
          phpize
          ./configure --enable-quicpro-sched
          make -j$(nproc)
          make TESTS="-j$(nproc) --show-diff"

  build-php-83:
    name: Build and Test PHP 8.3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies PHP 8.3
        run: |
          sudo apt-get update -yq
          sudo apt-get install -yq git build-essential autoconf pkg-config re2c bison libssl-dev zlib1g-dev ccache rustc cargo php8.3 php8.3-dev php8.3-xml

      - name: Setup ccache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Cargo vendor
        run: |
          cargo vendor > .cargo/config

      - name: Build & test extension PHP 8.3
        run: |
          phpize
          ./configure --enable-quicpro-sched
          make -j$(nproc)
          make TESTS="-j$(nproc) --show-diff"

  build-php-84:
    name: Build and Test PHP 8.4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies PHP 8.4
        run: |
          sudo apt-get update -yq
          sudo apt-get install -yq git build-essential autoconf pkg-config re2c bison libssl-dev zlib1g-dev ccache rustc cargo php8.4 php8.4-dev php8.4-xml

      - name: Setup ccache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Cargo vendor
        run: |
          cargo vendor > .cargo/config

      - name: Build & test extension PHP 8.4
        run: |
          phpize
          ./configure --enable-quicpro-sched
          make -j$(nproc)
          make TESTS="-j$(nproc) --show-diff"
